# Makefile.win32 for MSVC (NMake)
# Usage: Open "x86 Native Tools Command Prompt", then:
#   nmake -f Makefile.win32

CC = cl
LIB = lib
CFLAGS = /c /nologo /W3 /O2
LIBFLAGS = /nologo
TARGET = CgePix.lib

SOURCES = Color.c Pix.c
OBJECTS = $(SOURCES:.c=.obj)

$(TARGET): $(OBJECTS)
	$(LIB) $(LIBFLAGS) /OUT:$(TARGET) $(OBJECTS)

{.}.c{}.obj:
	$(CC) $(CFLAGS) /Fo$@ $<

clean:
	del $(OBJECTS) $(TARGET) 2>nul

.PHONY: clean
